### ISSUE TITLE
Bitrotted released pairs (summer 2022)

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/organisation#32] opened 2022-06-17 12:46 UTC
The lastest released version of these pairs no longer build for various reasons:
- [x] apertium-cat-ita : `Error (line 596): Invalid construction.`
- [x] apertium-dan-nor : `apertium-nob.nob.rlx: Error: Expected set on line 5830 near `)␊;␊#  "verken ... e`!`
- [x] apertium-fra-cat : `Error (line 229): Invalid construction.`
- [x] apertium-fra-frp : `Error at line 4615, column 23: Undefined attr-item lemg.`
- [x] apertium-nno-nob : `apertium-nob.nob.rlx: Error: Expected set on line 5830 near `)␊;␊#  "verken ... e`!`
- [x] apertium-oci-fra : `Error at line 4327, column 66: Undefined attr-item lemg.`
- [x] apertium-por-cat : `Error (line 632): Invalid construction.`
- [x] apertium-swe-nor : `apertium-nob.nob.rlx: Error: Expected set on line 5830 near `)␊;␊#  "verken ... e`!`

Ping @hectoralos @unhammer

**Comment by hectoralos** [comment] 2022-06-18 11:17
I am not sure what the errors are in the three Catalan-related pairs. I have found and corrected syntax errors in cat-ita (apparently, new versions of the compilers are stricter, which is to be welcomed). But I have not found anything of the kind in fra-cat or por-cat.

**Comment by TinoDidriksen** [comment] 2022-06-18 12:00
You shouldn't find anything in current HEAD of the repos. The point is that the listed pairs need new releases, because the current release has bitrotted.

**Comment by hectoralos** [comment] 2022-06-18 14:49
Sorry, I can't understand. I don't know what are the HEAD of the repos, nor what "bitrotted" means. I just add words and programme rules. I understand absolutely nothing about the arcana of Apertium.

**Comment by TinoDidriksen** [comment] 2022-06-18 14:56
For example, the latest release of apertium-cat-ita is https://github.com/apertium/apertium-cat-ita/releases/tag/v0.2.1 from 2019-11-20. That's what no longer builds, because the tools are now stricter.

There are 2 ways to fix that: Either patch the released tarball, or make a new release from current repository state. I would prefer a new release. So what I would like is for the relevant pair authors (which Github says is you and Unhammer) to sign off that current status is good enough, or to do minimal fixes to make current state good enough.

**Comment by hectoralos** [comment] 2022-06-18 15:13
OK, thanks for the clarification. I'll prepare new releases, hopefully during the next week.

**Comment by unhammer** [comment] 2022-06-30 19:33
Is there a deadline here for getting things into Debian? I'm going to be afk for most of July, so if it's before that then nno-nob/dan-nor could be tagged as they are (they're not completely consistent in the ->nno directions, but better than previous releases). 

Unfortunately swe->nno still has too many regressions (been too focused on nob->swe), so swe-nor would need a patch release if it has to happen during summer.

**Comment by TinoDidriksen** [comment] 2022-06-30 20:05
> Is there a deadline here for getting things into Debian?

The hard deadline is the Debian freeze starting on 2023-01-12, so there's no rush. It can wait the summer.

**Comment by hectoralos** [comment] 2022-08-29 19:39
`apertium-ita`, `apertium-cat-ita`, `apertium-por` and `apertium-por-cat` are ready to be packed for a new release. With this, everything pending in this issue related to Catalan should be solved. (BTW, thanks for the packing of `apertium-fra-cat`, @TinoDidriksen )

**Comment by TinoDidriksen** [comment] 2022-09-26 14:58
`cat-ita` and `por-cat` are now also released.

I've added `apertium-fra-frp` and `apertium-oci-fra` to the list of failures. I expect they just need to use latest released sources and verify that nothing broke.

**Comment by hectoralos** [comment] 2022-09-26 16:41
Thanks for the releases, @TinoDidriksen .
As for `apertium-fra-frp`, I'll solve it in the next days. No problem.
But for `apertium-oci-fra`, there is a problem. It is, in fact, release-ready for several months, but I am collaborating with an institution. We have agreed that first they will present it publicly. They will do it on 14 October (if they don't delay it again, as they have done several times). After that we will be able to make our release. What the bug is, it's already been solved some time ago in the version on GitHub.

**Comment by unhammer** [comment] 2022-10-23 07:21
* apertium-nno-nob:  3cfb292503f1b4ccf41c0db747ad3b70c92655e3 v1.5.0
  * apertium-nob:  8b75fddba5137405882afe72b0539c98075be7f3 v1.3.0
  * apertium-nno:  1054979a23978c6bd297271830c6efc75f4f492e v1.3.0

**Comment by hectoralos** [comment] 2022-10-31 12:20
`apertium-oci`, `apertium-frp`, `apertium-fra`, `apertium-oci-fra`, and `apertium-fra-frp` are ready to be packed for a new release.

**Comment by TinoDidriksen** [comment] 2022-11-01 13:35
Unfortunately, new `apertium-oci-fra` doesn't pass tests. Do you want tests ignored?

**Comment by TinoDidriksen** [comment] 2022-11-01 13:49
Nevermind, package oci-fra already ignores tests. As does fra-frp, but fra-frp passed them.

**Comment by hectoralos** [comment] 2022-11-01 15:49
I thought I passed all the tests. I'll take a look. For me, this is quite pro forma, because I really don't take care about this whole stuff. It find it too complex to manage.

**Comment by hectoralos** [comment] 2022-11-01 16:53
Yes, I think oci-fra can be released. The tests show several cases that are not working. They are not serious enough to stop creation of a release. I also see that there are things that had been assumed to be good but were not and are now fixed.

**Comment by unhammer** [comment] 2022-12-18 10:40
* https://github.com/apertium/apertium-swe-nor/releases/tag/v0.4.0  
* https://github.com/apertium/apertium-dan-nor/releases/tag/v1.5.0

both depend on the just-tagged commits of their monolingual dependencies

* https://github.com/apertium/apertium-dan/releases/tag/v0.7.0
* https://github.com/apertium/apertium-swe/releases/tag/v0.8.2
* https://github.com/apertium/apertium-nob/releases/tag/v1.4.0
* https://github.com/apertium/apertium-nno/releases/tag/v1.4.0

**Closed as completed** 2022-12-21 19:35 UTC
Labels: bug, help wanted
